# Generated by Django 3.1.6 on 2021-03-26 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vardas', models.CharField(max_length=300)),
                ('pavarde', models.CharField(max_length=300)),
                ('tipas', models.CharField(max_length=300)),
                ('data', models.DateField()),
            ],
        ),
    ]
