# Generated by Django 3.1.6 on 2021-03-26 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testing', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tracking_entry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vardas', models.CharField(max_length=300)),
                ('pavarde', models.CharField(max_length=300)),
                ('veiksmas', models.CharField(max_length=300)),
                ('data', models.DateField()),
            ],
        ),
    ]
