# Generated by Django 3.1.6 on 2021-03-27 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testing', '0002_tracking_entry'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='asmens_kodas',
            field=models.CharField(default=0, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tracking_entry',
            name='asmens_kodas',
            field=models.CharField(default='empty', max_length=20),
        ),
        migrations.AlterField(
            model_name='person',
            name='tipas',
            field=models.CharField(default='empty', max_length=300),
        ),
    ]
