# Generated by Django 3.1.6 on 2021-03-27 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testing', '0004_auto_20210327_0828'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='dienu_skaicius',
            field=models.IntegerField(),
        ),
    ]
